### PR TITLE
fix(desktop): move platform creation before event listener

### LINKED ISSUE #8657: Desktop typecheck error: Cannot find name 'platform'
## Description

Desktop package fails typecheck with error:
```
src/index.tsx:300:5 - error TS2304: Cannot find name 'platform'.
```

## Cause

PR #7360 introduced an event listener that references `platform.openLink()` before `platform` is defined.

## Impact

- Build fails on pre-push hook
- Cannot push to repository
- Introduced in commit 779610d66

## Expected Behavior

Typecheck should pass.

### PR DESCRIPTION
**Pull request by jerome-benoit**
### What does this PR do?

Fixes typecheck error `TS2304: Cannot find name 'platform'` introduced in #7360.

Moves `platform` and `serverPassword` creation outside `render()` so they're available to the click event listener that references `platform.openLink()`.

Fixes #8657

### How did you verify your code works?

- ✅ Typecheck passes: `bun run typecheck`
- ✅ Pre-push hooks pass (includes turbo typecheck)
- ✅ No functionality changes - only moves existing code to correct scope

### CODE REVIEW

**Comment by Eric-Guo** [comment]
LGTM!

**Comment by jerome-benoit** [comment]
fixed in dev
