### ISSUE TITLE
Preserve HTTP status on UnknownError so plugins can fallback

### ISSUE THREAD

**Issue by RaviTharuma** [anomalyco/opencode#47039]
## Summary
Provider HTTP failures (401, 429, 5xx, auth-expired) are often collapsed to UnknownError with Unexpected server error and no status on the session error. Plugins that implement model/provider fallback cannot classify the failure.

Related: https://github.com/anomalyco/opencode/issues/39340 (overloaded_error becomes UnknownError and is not retried).

## Repro
1. Point a provider baseURL at https://gateway.example/v1.
2. Have the gateway return 401 or 429 on chat completions.
3. opencode run -m provider/model-id ping

## Actual
CLI prints UnknownError / unexpected server error. Session error object has no HTTP status.

## Expected
Session error includes status (or original provider error name) so plugins can hop. User-visible message should include the status when known.

## Suggested fix
Propagate status / error.name from the AI SDK / fetch layer onto session.error instead of wrapping everything as UnknownError.

**Comment by RaviTharuma** [comment]
Both cited issues are still open, and neither covers this one.

- #30611 is about *whether* transient network errors get retried at all — retry policy inside OpenCode.
- #42513 asks for built-in auto-failover on rate limits — a feature request for OpenCode-side failover.

This issue is narrower and is a prerequisite for both: the session error object **loses the HTTP status** when a provider failure is wrapped as `UnknownError`. Whatever retries — OpenCode's own logic in #30611, the failover in #42513, or an external plugin — cannot classify 401 vs 429 vs 503 if the status was already discarded at the wrap site. Fixing the wrap does not implement either of those features, and implementing either of them without the status still leaves the classifier blind.

PR #47092 preserves the status on the Error wrap and does not change retry policy, which keeps it independent of the decisions still open on #30611 and #42513.
