### ISSUE TITLE
OpenCode does not persist thinking blocks for Claude Opus 4.7

### ISSUE THREAD

**Issue by renbou** [anomalyco/opencode#22852]
### Description

Claude Opus 4.7 omits thinking block contents by default: https://platform.claude.com/docs/en/about-claude/models/whats-new-claude-4-7#thinking-content-omitted-by-default

Setting a `display: summary` override does nothing - the thinking blocks are still hidden. However, the key problem is that this affects the agent not purely UI-wise: thinking blocks are not persisted in any way, meaning the agent cannot see thinking blocks from past turns. This makes the model pretty much unusable in OpenCode as it severely degrades its performance.

### OpenCode version

1.4.6

### Steps to reproduce

Add Claude Opus 4.7 to your config, try prompting the model to think across several tool calls, then on the next turn ask it to recall whether any thinking blocks are available

**Comment by rekram1-node** [comment]
If u use our variants in latest release they will be shown, also I think the blocks are persisted but only reasoning signatures not the summaries, so no impact to model perf but it does affect ur ux as a user

**Comment by NamedIdentity** [comment]
Was going crazy trying to figure out why thinking blocks were missing.

**Comment by cjnoname** [comment]
I still got the same issue if I switch the model from Bedrock Claude 4.7 to ChatGPT 5.4, even with this new version.

**Comment by rekram1-node** [comment]
@cjnoname not sure i follow

**Comment by cjnoname** [comment]
> [@cjnoname](https://github.com/cjnoname) not sure i follow

Thanks for the follow mate.

It’s very easy to reproduce.

First, ask “hello” in Bedrock Opus 4.7 (Build Mode).
Then switch to Plan Mode and ask “hello” in Copilot ChatGPT 5.4.
Next, switch back to Build Mode and ask “hello” again in Bedrock Opus 4.7.

You will then get the following error:

undefined: The model returned the following errors: {"type":"error","request_id":"req_wjzpzhh5jmyfkj5es5v7j3iuuf6z5ffciivto5idzqqdilm7ruta","error":{"type":"invalid_request_error","message":"messages.3.content.0.thinking.signature: Field required"}}

We use it everyday in this way and it only happens after we upgraded Opus to 4.7

**Comment by rekram1-node** [comment]
ahh okay i see why, ai sdk has inconsistent behaviors foir different providers. Should be an easy fix here

**Comment by cjnoname** [comment]
> ahh okay i see why, ai sdk has inconsistent behaviors foir different providers. Should be an easy fix here

Thanks dude. It would be very helpful for us :)

**Comment by cjnoname** [comment]
> ahh okay i see why, ai sdk has inconsistent behaviors foir different providers. Should be an easy fix here

Any chance for fixing this one mate? It's really a pain to use right now

**Comment by rekram1-node** [comment]
yeah i shall

**Comment by cjnoname** [comment]
> yeah i shall

It works now :) Tons of thanks
