### ISSUE TITLE
Bedrock authentication breaks with 1.16.0

### ISSUE THREAD

**Issue by darrinholst** [anomalyco/opencode#30946]
### Description

Getting the following after upgrading to 1.16.0

```
AWS credential provider failed: E is not a function. (In 'E(e)', 'E' is a Symbol). Please ensure your credential provider returns valid AWS credentials with accessKeyId and secretAccessKey properties.
```

We do use aws sso if that matters.

Downgrading back to 1.15.13 works

### OpenCode version

1.16.0
