### ISSUE TITLE
Desktop 1.18.4 renderer crash: TypeError on data.lsp (data shape mismatch)

### ISSUE THREAD

**Issue by megamen32** [anomalyco/opencode#38577]
## Desktop renderer crashes on launch in 1.18.4 with TypeError on `data.lsp`

**OpenCode Desktop**: 1.18.4 (packaged Electron, also reproduced after fresh reinstall via `brew install --cask opencode-desktop`)
**OpenCode CLI**: 1.18.4 (`~/.opencode/bin/opencode`)
**OS**: macOS (M-series, system `darwin`)
**Repro**: 100% on every launch after upgrade from 1.17.13 → 1.18.4. Earlier 1.17.13 launches were clean.

### Summary

The renderer crashes during initial load with `TypeError: (sync2(...).data.lsp ?? []).map is not a function`, immediately followed by a `fatal renderer error` and a burst of `Failed to load sessions TypeError: (x2.data ?? []).filter is not a function` (9+ times in ~2 s). The splash screen never resolves into the project picker.

### Logs (from `~/Library/Application Support/ai.opencode.desktop/logs/<timestamp>/renderer.log`)

```
[error] (renderer) fatal renderer error {
  error: 'TypeError: (sync2(...).data.lsp ?? []).map is not a function\n' +
    '    at Object.fn (oc://renderer/assets/main-BC_UeTC5.js:119587:35)\n' +
    '    at runComputation (...:487:22)\n' +
    '    at updateComputation (...:470:3)\n' +
    '    at runTop (...:566:7)\n' +
    '    at runQueue (...:638:45)\n' +
    '    at completeUpdates (...:594:5)\n' +
    '    at runUpdates (...:584:5)\n' +
    '    at completeLoad (...:167:5)\n' +
    '    at loadEnd (...:162:14)\n' +
    '    at oc://renderer/assets/main-BC_UeTC5.js:232:28'
}
[error] Failed to load sessions TypeError: (x2.data ?? []).filter is not a function   (×9)
[error] Failed to load sessions TypeError: (x2.data ?? []).filter is not a function
[2026-07-23 23:07:18.180] [error] [global-sdk] event stream error [object Object]
```

The exact lines in the bundled renderer (`/Applications/OpenCode.app/Contents/Resources/app.asar → out/renderer/assets/main-BC_UeTC5.js`):

```js
// line 119586-119587
mcp: Object.values(sync2().data.mcp ?? {}).map((item) => item.status),
lsp: (sync2().data.lsp ?? []).map((item) => item.status)
```

`mcp` is treated as an object map (`Object.values(... ?? {})`), `lsp` is treated as an array (`(... ?? []).map`). The `?? []`/`?? {}` fallback only catches `null`/`undefined`; if the server returns an object where an array is expected, `.map`/`filter` throw.

### What I already tried (none of this fixed it)

- Disabled all 4 plugins in `~/.config/opencode/opencode.json` (`plugin: []`).
- `rm -rf ~/.cache/opencode` (172 MB).
- Full restart of `OpenCode.app` multiple times.
- Verified `~/.config/opencode/plugins/` is empty.

Same crash, same stack trace, every time.

### Things that look relevant

- The `/lsp` HTTP endpoint of the local sidecar returns `[]` (an empty array) for my config (no `lsp` block in opencode.json, so LSP is disabled by default). So at least at first query the shape *is* an array.
- SDK type for `LspStatus` is `Array<LspStatus>` (see `packages/sdk/js/src/gen/types.gen.ts`).
- The renderer's `loadLspQuery` does `sdk.lsp.status().then((r2) => r2.data ?? [])`, which is consistent with the array expectation — so the *consumer* (`main-BC_UeTC5.js:119587`) and the *loader* disagree about what `data.lsp` is at the point the memo reads it.
- The same class of error existed in 1.17.13 too — I have older logs (`logs/20260719T192227/renderer.log`) showing `Failed to finish bootstrap instance TypeError: (x2.data ?? []).map is not a function`. There it was non-fatal. In 1.18.4 it became fatal and the `Failed to load sessions` variant also appears.

### Expected

Renderer should not crash when `data.lsp` is an object (or any non-array, non-null value). Defensive normalization (`Object.values(data.lsp ?? {})` or `Array.isArray(...) ? ... : []`) at the consumer would fix it without API changes.

### Environment

- macOS 15.x (arm64)
- `~/.config/opencode/opencode.json` has `mcp` with 8 servers and a custom `provider` block, but no `lsp` block.
- 4 plugins previously listed (`context-mode`, `opencode-glm-quota`, `opencode-codex-usage`, plus one npx-cached copy) — all removed before this report.

Happy to attach the full log archive, the asar extract, or run with `--print-logs` if useful.

**Comment by megamen32** [comment]
## Update: root cause was stale desktop runtime state, not 1.18.4

Closing this — **not a 1.18.4 bug**. Wiping the desktop runtime state fixed it.

### What actually fixed it

1. Quit `OpenCode.app`
2. `rm -rf ~/Library/Application Support/ai.opencode.desktop` (Local Storage, IndexedDB, `opencode.settings.dat`, `opencode.global.dat`, `opencode.workspace.*.dat`, Cache, logs, etc.)
3. `rm -rf ~/.local/share/opencode` (`auth.json`, `log/`, `project/`)
4. Replace `~/.config/opencode/opencode.json` with just `{ "$schema": "https://opencode.ai/config.json" }`
5. Relaunch — first launch onboarding runs, no errors.

Then I restored the full `opencode.json` (8 MCP servers, all `provider` block, all `mcp` config, `model`/`small_model` — just no `lsp`, no `plugin`) and **still no crash**. So the trigger was the accumulated desktop state, not the config.

### Hypothesis on the data shape

The renderer's `loadLspQuery` returns `sdk.lsp.status().then((r2) => r2.data ?? [])` and the consumer at `main-BC_UeTC5.js:119587` expects an array (`(... ?? []).map(...)`). My theory: somewhere in the stale Local Storage / IndexedDB / `opencode.global.dat` there was a serialized `data.lsp` blob from a prior app version that was an object (or `data.session` was an object), and the renderer was deserializing it back into a SolidJS store with the wrong shape, bypassing the fresh fetch from `loadLspQuery`. The first `loadEnd` tick then evaluated the memo against the stale shape and threw.

Same likely explanation for the `Failed to load sessions TypeError: (x2.data ?? []).filter is not a function` — `x2.data` was read from a stale deserialized snapshot, not a fresh array, so the sessions path crashed too.

### Repro now fails

With clean state, fresh app launches cleanly. Logs from the post-fix run:

```
[info] app starting { version: '1.18.4', packaged: true, onboardingTest: false }
[info] [server] Loaded shell environment with -il (52 vars)
[info] tauri migration: complete
[info] sidecar connection started { url: 'http://127.0.0.1:56692' }
[info] server ready { url: 'http://127.0.0.1:56692' }
[info] [desktop-onboarding] first launch onboarding evaluated
[info] [desktop-onboarding] starting first launch draft
```

No errors, no fatal, no `Failed to load sessions`, no `data.lsp` TypeError.

### Suggestion for the team

Two things that would have saved me an hour:

1. The docs' **"Reset desktop app storage (last resort)"** section could be promoted up next to "Disable plugins" / "Clear the cache" — these three should be presented as a single troubleshooting ladder, not as a fallback nobody scrolls to.
2. The defensive `?? []` / `?? {}` in the renderer's status-derived memos is a footgun. `Array.isArray(x) ? x : []` would have surfaced the wrong shape as a no-op instead of a fatal.

If anyone hits this in the future, the answer is: wipe `~/Library/Application Support/ai.opencode.desktop` + `~/.local/share/opencode` + minimal `opencode.json`. Their config (providers, MCP, plugins) can be restored afterward from backup and the app stays clean.

Sorry for the noise.
