### ISSUE TITLE
1.3.14: Embedded Bun fails to install plugins on Windows (broken node-gyp path)

### ISSUE THREAD

**Issue by shuff57** [anomalyco/opencode#21041]
## Bug Description

After upgrading from opencode 1.3.13 to 1.3.14 on Windows, external plugins (e.g. `oh-my-openagent`) fail to load. The embedded Bun runtime references a hardcoded CI build path for `node-gyp` that doesn't exist on user machines.

## Error

```
ERROR service=plugin pkg=oh-my-openagent version=latest error=Cannot find module '/home/runner/_work/opencode/opencode/node_modules/.bun/node-gyp@12.2.0/node_modules/node-gyp/bin/node-gyp.js' from 'B:\~BUN\root\src\index.js' failed to install plugin
```

## Steps to Reproduce

1. Install opencode 1.3.14 on Windows x64 (`npm install -g opencode-ai@1.3.14`)
2. Have a plugin configured in `opencode.json`: `"plugin": ["oh-my-openagent@latest"]`
3. Run `opencode` — plugin silently fails to load
4. Check logs at `~/.local/share/opencode/log/` — error shown above

## Root Cause

The embedded Bun binary inside `opencode-windows-x64` has a hardcoded path (`/home/runner/_work/opencode/opencode/node_modules/.bun/node-gyp@12.2.0/...`) that was baked in from the CI build environment. When opencode detects that `@opencode-ai/plugin` is not in the lockfile and attempts to reify dependencies, the embedded Bun tries to invoke `node-gyp` via that non-existent path and fails.

On 1.3.13, the npm dependency check either doesn't trigger or uses a working path — plugins load fine.

## Workaround

Downgrade to 1.3.13:

```bash
npm install -g opencode-ai@1.3.13
```

## Environment

- **OS:** Windows 11 Home 10.0.26200 (x64)
- **opencode:** 1.3.14 (broken), 1.3.13 (working)
- **System Bun:** 1.3.11
- **Plugin:** oh-my-openagent@3.15.0
- **Install method:** npm global

**Comment by thdxr** [comment]
dupe, fix going out now
