### ISSUE TITLE
Copy function broken in Windows 11 Terminal and Warp (v1.1.49)

### ISSUE THREAD

**Issue by zhongwei** [anomalyco/opencode#11904]
### Description

Version 1.1.49 cannot copy content in Windows 11 Terminal or Warp Terminal. Version 1.1.48 works fine.

**Comment by jc01rho** [comment]
same here, from 1.1.49, just terminal also occured

**Comment by zhangzhenxiang666** [comment]
The same applies to WSL Ubuntu 24

**Comment by Her-xanadu** [comment]
The same applies to Mac,but l can input image by ctrl+c now

**Comment by niushuai1991** [comment]
The same issue occurs in WSL ArchLinux

**Comment by ErcinDedeoglu** [comment]
https://github.com/anomalyco/opencode/issues/11909 same.

**Comment by umutaxoy** [comment]
Update: Tested different versions. Copy-on-selection works in 1.1.48 but broken in 1.1.49, 1.1.50, and beta. The regression was introduced in version 1.1.49.

**Comment by kommander** [comment]
@umutaxoy what platform and terminal? With tmux? Via ssh?

**Comment by jc01rho** [comment]
v1.1.50 still doesn't fix the issue. issue is still exist.

**Comment by umutaxoy** [comment]
> [@umutaxoy](https://github.com/umutaxoy) what platform and terminal? With tmux? Via ssh?

@kommander Platform & Teheadless server, no GUI)Connection: SSH via VS Code Remote SSH, also tested with Warp termina VS Code Remote SSH, also tested with Warp terminal and natreen: RuiplexerTERM: xtrectly in shellddititerminal multiplexerTERM: xterm-256colorAddititerminal multiplexerTERM: xterm-256colorAdditional tes1.1.48 works perfectly - copy on selection ng:1.1.48 works perfectly - copy on selection ng:1.1.48 works perfectly - copy on selection fntroducss to ba regression in 1.1.49. Downgrading t seems to be a regression in 1.1.49. Downgrading t seems to be a regression in 1.1.49. Downgrading to 1.1.48 is a working workaround.

**Comment by jcowles** [comment]
Also happening on windows with WezTerm and opencode 1.1.50
exact error is `renderer.CopyToClipboardOSC52 is not a function`

Mine is also a local build, so I'm starting to think the upgrade of opentui vs. my local packages is the culprit
https://github.com/anomalyco/opencode/commit/994c55f7

**Comment by jcowles** [comment]
Confirmed, my error was due to outdated packages -- after bun install, it's working again

**Comment by jc01rho** [comment]
reinstall v1.1.51  with bun add -g opencode-ai, with tmux set -g allow-passthrough on works

**Comment by umutaxoy** [comment]
The problem appears to be resolved with version 1.1.51. @kommander
