### ISSUE TITLE
Desktop typecheck error: Cannot find name 'platform'

### ISSUE THREAD

**Issue by jerome-benoit** [anomalyco/opencode#8657]
## Description

Desktop package fails typecheck with error:
```
src/index.tsx:300:5 - error TS2304: Cannot find name 'platform'.
```

## Cause

PR #7360 introduced an event listener that references `platform.openLink()` before `platform` is defined.

## Impact

- Build fails on pre-push hook
- Cannot push to repository
- Introduced in commit 779610d66

## Expected Behavior

Typecheck should pass.
