### ISSUE TITLE
Bedrock not working in 0.1.136

### ISSUE THREAD

**Issue by madisonbullard** [anomalyco/opencode#396]
Here is my config:
```json
   {
     "$schema": "https://opencode.ai/config.json",
     "theme": "catppuccin",
     "model": "amazon-bedrock/anthropic.claude-3-7-sonnet-20250219-v1:0",
     "autoshare": false,
     "autoupdate": true
   }
```

Seeing this error: `AI_APICallError: undefined: Invocation of model ID anthropic.claude-3-7-sonnet-20250219-v1:0 with on-demand throughput isn’t supported. Retry your request with the ID or ARN of an inference profile that contains this model`

I saw this issue, and the resulting PR: https://github.com/sst/opencode/issues/136
But the logs for my session don't indicate that the region code is being prepended to the model ID. Shouldn't I expect to see `modelID=us.anthropic....`?

Here are logs for my session:
```
INFO  2025-06-25T15:18:29 +196ms service=default version=0.1.129 args= opencode
INFO  2025-06-25T15:18:29 +2ms service=app cwd=/Users/madisonbullard/Documents/Projects/stellm creating
INFO  2025-06-25T15:18:29 +13ms service=app git=/Users/madisonbullard/Documents/Projects/stellm git
INFO  2025-06-25T15:18:29 +4ms service=app name=provider registering service
INFO  2025-06-25T15:18:29 +1ms service=app name=config registering service
INFO  2025-06-25T15:18:29 +12ms service=config $schema=https://opencode.ai/config.json theme=catppuccin autoshare=false autoupdate=true model=amazon-bedrock/anthropic.claude-3-7-sonnet-20250219-v1:0 loaded
INFO  2025-06-25T15:18:29 +4ms service=models.dev refreshing
INFO  2025-06-25T15:18:29 +6ms service=provider init
INFO  2025-06-25T15:18:30 +219ms service=provider providerID=openai found
INFO  2025-06-25T15:18:30 +1ms service=provider providerID=amazon-bedrock found
INFO  2025-06-25T15:18:30 +0ms service=app name=share registering service
INFO  2025-06-25T15:18:30 +0ms service=bus type=storage.write subscribing
INFO  2025-06-25T15:18:30 +0ms service=app name=bus registering service
INFO  2025-06-25T15:18:30 +337ms service=server method=POST path=/config_get request
INFO  2025-06-25T15:18:30 +3ms service=server duration=3 response
INFO  2025-06-25T15:18:30 +30ms service=server method=GET path=/event request
INFO  2025-06-25T15:18:30 +0ms service=server event connected
INFO  2025-06-25T15:18:30 +6ms service=bus type=* subscribing
INFO  2025-06-25T15:18:30 +2ms service=server duration=8 response
INFO  2025-06-25T15:18:30 +26ms service=server method=POST path=/provider_list request
INFO  2025-06-25T15:18:30 +6ms service=server duration=6 response
INFO  2025-06-25T15:18:32 +2148ms service=installation method=curl target=0.1.136 stdout=[0;32mInstalled version: [1;33m.[0m
[0;32mDownloading [38;2;255;140;0mopencode [0;32mversion: [1;33m0.1.136 [0;32m...[0m
 stderr=#=#=#                                                                          
##O#-#                                                                         

                                                                           1.0%
########                                                                  12.3%
##################                                                        26.1%
############################                                              40.2%
#######################################                                   54.3%
#################################################                         68.3%
#####################################################                     74.7%
###############################################################           88.1%
######################################################################## 100.0%
 upgraded
INFO  2025-06-25T15:18:32 +0ms service=bus type=installation.updated publishing
INFO  2025-06-25T15:18:38 +6140ms service=server method=POST path=/session_create request
INFO  2025-06-25T15:18:38 +7ms service=session id=ses_858549436ffeXJ2HH7voey84UM version=0.1.129 title=New Session - 2025-06-25T15:18:38.797Z time=[object Object] created
INFO  2025-06-25T15:18:38 +0ms service=app name=session registering service
INFO  2025-06-25T15:18:38 +0ms service=app name=storage registering service
INFO  2025-06-25T15:18:38 +0ms service=storage path=/Users/madisonbullard/.local/share/opencode/project/Users-madisonbullard-Documents-Projects-stellm/storage init
INFO  2025-06-25T15:18:38 +3ms service=bus type=storage.write publishing
INFO  2025-06-25T15:18:38 +1ms service=bus type=session.updated publishing
INFO  2025-06-25T15:18:38 +0ms service=server duration=11 response
INFO  2025-06-25T15:18:38 +16ms service=server method=POST path=/session_chat request
INFO  2025-06-25T15:18:38 +10ms service=session session=ses_858549436ffeXJ2HH7voey84UM chatting
INFO  2025-06-25T15:18:38 +0ms service=provider providerID=amazon-bedrock modelID=anthropic.claude-3-7-sonnet-20250219-v1:0 getModel
INFO  2025-06-25T15:18:38 +1ms service=provider status=started providerID=amazon-bedrock getSDK
INFO  2025-06-25T15:18:38 +2ms service=server method=POST path=/session_messages request
INFO  2025-06-25T15:18:38 +73ms service=provider status=completed duration=75 providerID=amazon-bedrock getSDK
INFO  2025-06-25T15:18:38 +0ms service=provider providerID=amazon-bedrock modelID=anthropic.claude-3-7-sonnet-20250219-v1:0 found
INFO  2025-06-25T15:18:38 +1ms service=server duration=74 response
INFO  2025-06-25T15:18:38 +0ms service=session sessionID=ses_858549436ffeXJ2HH7voey84UM locking
INFO  2025-06-25T15:18:38 +26ms service=bus type=storage.write publishing
INFO  2025-06-25T15:18:38 +1ms service=bus type=message.updated publishing
INFO  2025-06-25T15:18:39 +94ms service=bus type=storage.write publishing
INFO  2025-06-25T15:18:39 +0ms service=bus type=message.updated publishing
INFO  2025-06-25T15:18:39 +2ms service=app name=mcp registering service
ERROR 2025-06-25T15:18:40 +1118ms service=session error=AI_APICallError: undefined: Invocation of model ID anthropic.claude-3-7-sonnet-20250219-v1:0 with on-demand throughput isn’t supported. Retry your request with the ID or ARN of an inference profile that contains this model. callback error
INFO  2025-06-25T15:18:40 +2ms service=bus type=session.error publishing
INFO  2025-06-25T15:18:40 +6ms service=session session=ses_858549436ffeXJ2HH7voey84UM type=error part
INFO  2025-06-25T15:18:40 +0ms service=session session=ses_858549436ffeXJ2HH7voey84UM type=error unhandled
INFO  2025-06-25T15:18:40 +7ms service=bus type=storage.write publishing
INFO  2025-06-25T15:18:40 +0ms service=bus type=message.updated publishing
INFO  2025-06-25T15:18:40 +0ms service=session sessionID=ses_858549436ffeXJ2HH7voey84UM unlocking
INFO  2025-06-25T15:18:40 +4ms service=server duration=1347 response
```

**Comment by madisonbullard** [comment]
Oh this was a problem with my env setup. I had to declare `AWS_REGION` explicitly.

I previously had `AWS_PROFILE` defined in `.env`, and that profile declares a region (us-east-1), but I did not have `AWS_REGION` set. Adding `AWS_REGION=us-east-1` to `.env` fixed it.

I thought [this code setting a default region](https://github.com/sst/opencode/blob/0fc8dfc77e88bcbc40f61f4f799e51e65e886b25/packages/opencode/src/provider/provider.ts#L120) would make this step unnecessary.
