### ISSUE TITLE
Is there any support for running OpenCode on MacOS older version?

### ISSUE THREAD

**Issue by visbigHQ** [anomalyco/opencode#6038]
### Question

I installed opencode using curl script command and I also tried installing from dmg file but opencode doesn't seem to work on MacOS older versions. This is extremely bad experience. I'm using MacOS Big Sur and I have intel MacBook. I need help.

**Comment by akemmanuel** [comment]
You can run it with Docker. You need to find a old version of Docker Desktop (which is compatible with your MacOS) and install it. The command to run it afterwards is `docker run -it --rm ghcr.io/sst/opencode`

**Comment by rekram1-node** [comment]
whats the issue u encountered

**Comment by sujayxaradhya** [comment]
> whats the issue u encountered

I got that opencode is built for MacOS 13 or later. When I ran npm command to install from Docs.

When I ran `opencode` in terminal after installing it with npm.

I'm an Intel MacBook Big Sur user and will not get any update more than that from Apple and because of this reason sadly I can't able to use OpenCode.

I believe the same problem is with @visbigHQ as well.

**Comment by akemmanuel** [comment]
> You can run it with Docker. You need to find a old version of Docker Desktop (which is compatible with your MacOS) and install it. The command to run it afterwards is `docker run -it --rm ghcr.io/sst/opencode`

I tried on MacOS 11 and it works

**Comment by rekram1-node** [comment]
But what's the issue you encountered? I see no errors?

**Comment by visbigHQ** [comment]
> But what's the issue you encountered? I see no errors?

I got the following errors: 

```
Command -> opencode
Output -> dyld: Symbol not found: _ubrk_clone
  Referenced from: /Users/sujayxaradhya/.opencode/bin/opencode (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libicucore.A.dylib

[1]    80334 abort      opencode
```

**Comment by shutup** [comment]
i encounter the same issue,i am not sure why this should happen, my mbp cannot upgrade to new system version,and i think the issue is very easy to solve, for bun , bun v1.1.20 runs on Big Sur but v1.1.21 doesn't. and the issue happen every few version, i think  it is just a compatible issue,maybe a build setting,why it such difficult to solve
dyld: Symbol not found: _ubrk_clone
  Referenced from: /Users/xxx/.bun/install/global/node_modules/opencode-darwin-x64/bin/opencode (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libicucore.A.dylib

**Comment by cnscottluo** [comment]
same issue

**Comment by TonyZhang1993** [comment]
> > But what's the issue you encountered? I see no errors?
> 
> I got the following errors:
> 
> ```
> Command -> opencode
> Output -> dyld: Symbol not found: _ubrk_clone
>   Referenced from: /Users/sujayxaradhya/.opencode/bin/opencode (which was built for Mac OS X 13.0)
>   Expected in: /usr/lib/libicucore.A.dylib
> 
> [1]    80334 abort      opencode
> ```

same issue, looking forward the solution.
ps. I'm an Intel MacBook Big Sur user,  Neither the OpenCode Terminal nor  OpenCode Desktop (Beta)  is functioning properly.  :(

**Comment by alexkkss** [comment]
I encountered the same problem. 
Do I need to upgrade to macOS？(macOs 12.2.1)

```
dyld[20094]: Symbol not found: _ubrk_clone
  Referenced from: /Users/mobvista/.opencode/bin/opencode
  Expected in: /usr/lib/libicucore.A.dylib
[1]    20094 abort      opencode
```



---------
Update
Upgrading from 12.2.1 to 12.7.6 resolved this issue，OpenCode Terminal works

**Comment by TonyZhang1993** [comment]
> > > But what's the issue you encountered? I see no errors?
> > 
> > 
> > I got the following errors:
> > ```
> > Command -> opencode
> > Output -> dyld: Symbol not found: _ubrk_clone
> >   Referenced from: /Users/sujayxaradhya/.opencode/bin/opencode (which was built for Mac OS X 13.0)
> >   Expected in: /usr/lib/libicucore.A.dylib
> > 
> > [1]    80334 abort      opencode
> > ```
> 
> same issue, looking forward the solution. ps. I'm an Intel MacBook Big Sur user, Neither the OpenCode Terminal nor OpenCode Desktop (Beta) is functioning properly. :(

update here.
After I updated MacOS to 12.7.4 (21H1123), Opencode works fine.

**Comment by alexkkss** [comment]
> 我也遇到了同样的问题，我不确定为什么会发生这种情况。我的 MacBook Pro 无法升级到新的系统版本。我认为这个问题很容易解决，因为 Bun 1.1.20 版本可以在 Big Sur 上运行，但 1.1.21 版本却不行。而且这个问题每隔几个版本就会出现一次。我认为这只是一个兼容性问题，可能是构建设置的问题。为什么解决起来这么困难呢？ dyld 错误信息为：找不到符号：_ubrk_clone。 引用自：/Users/xxx/.bun/install/global/node_modules/opencode-darwin-x64/bin/opencode（该文件是为 Mac OS X 13.0 构建的）。 预期位于：/usr/lib/libicucore.A.dylib。

Upgrading from 12.2.1 to 12.7.6 resolved this issue

**Comment by Zourunfa** [comment]
Is there a way to do this without updating the system?

**Comment by shd0812** [comment]
the same error

dyld[35216]: Symbol not found: _ubrk_clone
  Referenced from: /Users/xxx/.nvm/versions/node/v20.20.0/lib/node_modules/opencode-ai/node_modules/opencode-darwin-x64/bin/opencode
  Expected in: /usr/lib/libicucore.A.dylib
