### ISSUE TITLE
v1.16.0 regression: AWS credential provider fails with "E is not a function. (In 'E(e)', 'E' is a Symbol)" on Bedrock

### ISSUE THREAD

**Issue by pjayala** [anomalyco/opencode#30918]
## Bug report

**opencode version:** 1.16.0
**Platform:** macOS (darwin)
**Provider:** Amazon Bedrock (`amazon-bedrock/global.anthropic.claude-sonnet-4-6`)

## Error message

AWS credential provider failed: E is not a function. (In 'E(e)', 'E' is a Symbol). Please ensure your credential provider returns valid AWS credentials with accessKeyId and secretAccessKey properties.

## Expected behavior

Credential provider resolves successfully as it did in v1.15.13.

## Root cause hypothesis

This appears to be a bundler minification regression introduced by the 38% startup-time improvement in PR #30453. A JavaScript `Symbol` is being minified to `E` and then called as a function (`E(e)`), which throws because Symbols are not callable. The AWS SDK credential chain uses Symbol-based iterators/generators during provider resolution which are sensitive to this kind of minification.

Downgrading to v1.15.13 resolves the issue.

## Workaround

Downgrade to v1.15.13.

### OpenCode version

1.16.0

### Steps to reproduce

1. Upgrade from v1.15.13 to v1.16.0
2. Start opencode with an Amazon Bedrock provider configured
3. Error appears on startup during AWS credential chain resolution

### Operating System

macOS (darwin)

### Terminal

wezterm
