### ISSUE TITLE
Session history disappear after updating

### ISSUE THREAD

**Issue by So-cean** [anomalyco/opencode#35690]
## OpenCode Version

1.17.14

## Reproduction Steps

1. Have OpenCode v1.17.13 installed and used for several weeks, accumulating many sessions.
2. Allow OpenCode to auto-update to v1.17.14 (or restart it after it updates itself).
3. Start OpenCode: `opencode --port 36996`
4. Observe that the server either crashes with `JSON.parse(...).map is not a function` or starts but historical sessions open to a blank conversation pane.
5. Check `~/.local/share/opencode/opencode.db`: `message` and `part` tables still contain all data, but `session_message` / `session_input` / `session_context_epoch` are empty.

## Expected Behavior

After an automatic update, all previously existing sessions and their conversation history should remain visible and readable in the TUI. Data that is still present in `opencode.db` should be migrated or continue to be read by the new version.

## Actual Behavior

- The TUI shows the session list, but every historical session opens with no messages.
- The underlying `message`/`part` data is preserved, suggesting a regression in how v1.17.14 loads legacy session data rather than actual data loss.

## Screenshots / Share Links

N/A — the issue is reproducible from the local database state. Relevant logs and DB dumps can be provided on request.

## Operating System

Linux (OpenCode binary running on a remote Linux workstation, accessed via SSH)

## Terminal

SSH terminal (issue reproduces regardless of local terminal emulator)

**Comment by So-cean** [comment]
## OpenCode Version

1.17.14

## Reproduction Steps

1. Have OpenCode v1.17.13 installed and used for several weeks, accumulating many sessions.
2. Allow OpenCode to auto-update to v1.17.14 (or restart it after it updates itself).
3. Start OpenCode: `opencode --port 36996`
4. Observe that the server either crashes with `JSON.parse(...).map is not a function` or starts but historical sessions open to a blank conversation pane.
5. Check `~/.local/share/opencode/opencode.db`: `message` and `part` tables still contain all data, but `session_message` / `session_input` / `session_context_epoch` are empty.

## Expected Behavior

After an automatic update, all previously existing sessions and their conversation history should remain visible and readable in the TUI. Data that is still present in `opencode.db` should be migrated or continue to be read by the new version.

## Actual Behavior

- The TUI shows the session list, but every historical session opens with no messages.
- The underlying `message`/`part` data is preserved, suggesting a regression in how v1.17.14 loads legacy session data rather than actual data loss.

## Screenshots / Share Links

N/A — the issue is reproducible from the local database state. Relevant logs and DB dumps can be provided on request.

## Operating System

Linux (OpenCode binary running on a remote Linux workstation, accessed via SSH)

## Terminal

SSH terminal (issue reproduces regardless of local terminal emulator)

**Comment by yugdabgar21** [comment]
I am facing the exact same issue on **Windows 11 Home** with **OpenCode Desktop v1.17.14**.

After updating to v1.17.14:
- The "thinking" state never renders.
- The interface goes completely blank immediately after submitting a task.
- Restarting the IDE temporarily fixes it, but the cycle repeats (blank screen on the next task).

This confirms the regression affects the Windows Desktop build as well, not just Linux/SSH environments. The session list is visible, but every session opens with no messages.

**Comment by So-cean** [comment]
这个发现很关键！opencode 1.17.14 有 schema 校验：
1. Workspace ID 必须以 wrk 开头（不是 ws_）
2. Project commands 不能是 []
