### ISSUE TITLE
Error using cloudflare AI gateway models

### ISSUE THREAD

**Issue by zhabiba24** [anomalyco/opencode#13758]
### Description

Get this error `TypeError: sdk.languageModel is not a function. (In 'sdk.languageModel(model.api.id)', 'sdk.languageModel' is undefined)` when trying to use `workers-ai/@cf/openai/gpt-oss-120b` after conencting with cloudflare AI gateway

### OpenCode version

1.1.48

### Steps to reproduce

1. Hit /connect
2. Follow steps to authenticate to cloudflare AI gateway
3. Select GPT OSS 120B
4. Type something and hit return to start flow

### Operating System

Mac OS

### Terminal

iterm2

**Comment by zhabiba24** [comment]
Not a duplicate, similar looking but different error and in a newer version since that was relased

**Comment by rekram1-node** [comment]
You are on an old version of opencode, if you upgrade this is resolved

**Comment by zhabiba24** [comment]
Thanks, went away. I think I actually had a seaparte issue - I was running `opencode upgrade` and while it said method brew, it didn't actually upgrade the binary (got same version after running it). So thought I was on latest.

Then when I ran `brew upgrade opencode` just now the version got bumped and it's all working

**Comment by rekram1-node** [comment]
Yeah that's also an old bug, should also be fixed. 

Also make sure u use our tap:
brew install anomalyco/tap/opencode

**Comment by zhoukekestar** [comment]
still not work, because the npm package `ai-gateway-provider` is not compatible with the opencode provider, no languageModel method can be invoked，https://github.com/cloudflare/ai/blob/fe208aae1ff4a6000274436a348c2243b2447ea9/packages/ai-gateway-provider/src/index.ts#L252

<img width="1112" height="647" alt="Image" src="https://github.com/user-attachments/assets/1067b212-001a-4052-b2b1-c94d90243097" />

**Comment by orionstudt** [comment]
I am getting this on `1.2.15`.

I am configured with Cloudflare AI Gateway and trying to use `cloudflare-ai-gateway/anthropic/claude-sonnet-4-6`

Logs:

```
WARN  2026-02-27T22:38:41 +726ms service=bun pkg=ai-gateway-provider cachedVersion=3.1.1 Failed to resolve latest version, using cached
INFO  2026-02-27T22:38:41 +2ms service=provider status=completed duration=11137 providerID=cloudflare-ai-gateway getSDK
ERROR 2026-02-27T22:38:41 +18ms service=session.processor error=sdk.languageModel is not a function. (In 'sdk.languageModel(model.api.id)', 'sdk.languageModel' is undefined) stack="TypeError: sdk.languageModel is not a function. (In 'sdk.languageModel(model.api.id)', 'sdk.languageModel' is undefined)\n    at getLanguage (src/provider/provider.ts:1181:15)\n    at processTicksAndRejections (native:7:39)" process
```

For additional context I'm actually using the official cloudflare sandbox image `0.7.8`: https://hub.docker.com/layers/cloudflare/sandbox/0.7.8-opencode/images/sha256-ec3f866fc3bb3b2e12f789498b191afc1789371f06abb54f73d01da5bc91e20b

**Comment by orionstudt** [comment]
@rekram1-node I'd like to re-open this ticket.

Is there anything we can do here?

See these logs from today:

```shell
[15:08:59] josh.studt ~/code
$ opencode --version
1.2.17
[15:09:02] [cost 0.691s] opencode --version


[15:09:03] josh.studt ~/code
$ opencode run "What is cloudflare?" -m cloudflare-ai-gateway/anthropic/claude-sonnet-4-6

> build · anthropic/claude-sonnet-4-6

Error: TypeError: sdk.languageModel is not a function. (In 'sdk.languageModel(model.api.id)', 'sdk.languageModel' is undefined)
```

Here are the debug logs:

```shell
INFO  2026-03-04T23:14:20 +1ms service=session.processor process
INFO  2026-03-04T23:14:20 +0ms service=llm providerID=cloudflare-ai-gateway modelID=anthropic/claude-sonnet-4-6 sessionID=ses_344de8054ffeMH19j1y7Fk1AIr small=false agent=build mode=primary stream
INFO  2026-03-04T23:14:20 +0ms service=provider status=started providerID=cloudflare-ai-gateway getSDK
INFO  2026-03-04T23:14:20 +1ms service=bus type=session.diff publishing
WARN  2026-03-04T23:14:21 +301ms service=bun pkg=ai-gateway-provider cachedVersion=3.1.1 Failed to resolve latest version, using cached
INFO  2026-03-04T23:14:21 +2ms service=provider status=completed duration=311 providerID=cloudflare-ai-gateway getSDK
ERROR 2026-03-04T23:14:21 +0ms service=default e=sdk.languageModel is not a function. (In 'sdk.languageModel(model.api.id)', 'sdk.languageModel' is undefined) rejection
WARN  2026-03-04T23:14:21 +261ms service=bun pkg=ai-gateway-provider cachedVersion=3.1.1 Failed to resolve latest version, using cached
INFO  2026-03-04T23:14:21 +1ms service=provider status=completed duration=565 providerID=cloudflare-ai-gateway getSDK
ERROR 2026-03-04T23:14:21 +1ms service=session.processor error=sdk.languageModel is not a function. (In 'sdk.languageModel(model.api.id)', 'sdk.languageModel' is undefined) stack="TypeError: sdk.languageModel is not a function. (In 'sdk.languageModel(model.api.id)', 'sdk.languageModel' is undefined)\n    at getLanguage (src/provider/provider.ts:1202:15)\n    at processTicksAndRejections (native:7:39)" process
INFO  2026-03-04T23:14:21 +1ms service=bus type=session.error publishing
INFO  2026-03-04T23:14:21 +0ms service=bus type=session.status publishing
INFO  2026-03-04T23:14:21 +0ms service=bus type=session.idle publishing
INFO  2026-03-04T23:14:21 +4ms service=bus type=message.updated publishing
INFO  2026-03-04T23:14:21 +1ms service=session.compaction pruning
INFO  2026-03-04T23:14:21 +1ms service=session.prompt sessionID=ses_344de8054ffeMH19j1y7Fk1AIr cancel
INFO  2026-03-04T23:14:21 +0ms service=bus type=session.status publishing
INFO  2026-03-04T23:14:21 +0ms service=bus type=session.idle publishing
Error: TypeError: sdk.languageModel is not a function. (In 'sdk.languageModel(model.api.id)', 'sdk.languageModel' is undefined)
INFO  2026-03-04T23:14:21 +1ms service=session.compaction pruned=0 total=0 found
INFO  2026-03-04T23:14:21 +0ms service=default directory=/Users/josh.studt/code disposing instance
INFO  2026-03-04T23:14:21 +1ms service=state key=/Users/josh.studt/code waiting for state disposal to complete
INFO  2026-03-04T23:14:21 +0ms service=state key=/Users/josh.studt/code state disposal completed
```

**Comment by jorismak** [comment]
this works for me, _after_ setting `CLOUDFLARE_ACCOUNT_ID` and `CLOUDFLARE_GATEWAY_ID`.

cd account id is my general CF account id,
gateway id is the name of the gateway I created (apparently didn't use the default one).

after that, give  the authentication when opencode asks for it.

Works on 1.2.27, tested Nemotron and Kimi K2.5.

**Comment by wdalhaj** [comment]
this might be weird but installing `ai` package globally via `npm` solved the problem for me. I cant recall if i did somthing else.

```bash
npm i -g ai
```

**Comment by d7p** [comment]
I had the same issue on 1.15.12 and globally installing ai worked for me
